apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  namespace: ns-tarun
  labels:
    app: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: tarungarg1208/nagp-devops-assign-1:1
          ports:
            - name: http
              containerPort: 7100
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: node-app
spec:
  type: NodePort
  selector: 
    app: node-app
  ports:
    - protocol: TCP
      nodePort: 30158
      targetPort: 7100
      port: 30158
